### ISSUE TITLE
Port Configuration more flexible

### ISSUE THREAD

**Issue by xohudson** [alinmear/docker-conanexiles#12]
Hi,

Can u make a more flexible Port Configuration (so we can host multiple Server at 1 IP Adress) e.g.

````
**StartServer.bat**

Single server (simple)

ConanSandboxServer.exe -log
Multiple servers (advanced)

ConanSandboxServer.exe -log -MaxPlayers=50 -Port=7777 -QueryPort=27015 -usedir=SERVER1
ConanSandboxServer.exe -log -MaxPlayers=50 -Port=7779 -QueryPort=27017 -usedir=SERVER2
ConanSandboxServer.exe -log -MaxPlayers=50 -Port=7781 -QueryPort=27019 -usedir=SERVER3
````

**Comment by alinmear** [comment]
After investigating this issue i think hosting several processes within the same container should be avoided at all. 

We can handle most of this with docker itself, having process separation and more flexibility about our setup and keeping it simple at all.

All we have to do is to introduce the `-usedir` switch (this could be the service name to keep the management simple). Instead of hosting multiple exile processes (servers) within the same container, we should create a shared volume with our server data and with different configuration folders, as it would be with the "multiple servers" approach. But we don't have to deal with all the port configuration within 1 container; we can keep the port configuration the same for each docker container but binding it to the host; this keeps the setup simple and straight forward. Also for monitoring, updating and restarting we have clear separation on container level instead of process level.

I am trying to explain this with a simple compose example, which is sharing the data volume :

```
version: '2'

services:
  conanexiles1:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
        - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='My Cool Server'"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles

  conanexiles2:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
        - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='My Cool Server'"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
    ports:
        - 7777:7779/udp
        - 27015:27017/udp
    volumes:
        - data:/conanexiles

volumes:
    data:
        driver: local 
```

Tasks we have to do:
- Introduce the switch `-usedir` = servicename
- Introduce a master slave logic for upgrading the server version via redis

Note: We could use the same logic for RCon messages between multliptle server instances

**Comment by alinmear** [comment]
This would be a major change, so after implementing this, we should start creating a version scheme because this could break server setups after upgrading.

**Comment by xohudson** [comment]
Will this work??? 

The Ports 7777 / 27015 from outside to multiple Ports inside???

>  ports:
>         - 7777:7777/udp
>         - 7778:7778/udp
>         - 27015:27015/udp
> 
>   ports:
>         - 7777:7779/udp
>         - 27015:27017/udp

**Comment by alinmear** [comment]
@xohudson  you are totally right. I just misstipped the port config. It should be the other way... Updated my comment.

**Comment by alinmear** [comment]
@xohudson can you do some testing with the new logic from branch #12. Local tests just went fine but there are some major changes, so we should make qa.

**Comment by alinmear** [comment]
Changes are merged into master.

**Comment by xohudson** [comment]
Hey there.. Sorry for late posting but now i just tested theMultiserver branch. Both Server are in the Server list but the second is only joinable by Direct connection via IP+Port

Is there a chance to make Port configuration by direct Port ? Not by Port detour???

Thanks for the Multisupport

**Comment by alinmear** [comment]
Ok, lets investigate this issue. Reopening ...

**Comment by alinmear** [comment]
We could already  accomplish this by using the env var:

- "CONANEXILES_CMDSWITCHES=-Port=7779 -QueryPort=27017"

But for cleaner configuration we should introduce 2 env variables:

- CONANEXILES_PORT
- CONANEXILES_QUERYPORT

So for the multinstance setup we would have 3 variables:

- CONANEXILES_INSTANCENAME
- CONANEXILES_PORT
- CONANEXILES_QUERYPORT

**Comment by xohudson** [comment]
I will Test this in The evening today.

**Comment by xohudson** [comment]
Hi, so i went try and error but nothing themes to be right.

my docker-compose.yml:

```
version: '2'

services:
  conanexiles0:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
      - "CONANEXILES_SERVER_TYPE=pve"
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=****"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='xo11.de - Inside'"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=****"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=****"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"

    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
        - 25575:25575/tcp #i need it for UptimeRobot (TCP-Port)

    volumes:
        - /gameserver/conan/server1:/conanexiles
       
  conanexiles1:
    image: alinmear/docker-conanexiles
    restart: always
    environment:
      - "CONANEXILES_SERVER_TYPE=pvp"
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=****"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName='xo11.de - Public PvP'"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword="
      - "CONANEXILES_MASTERSERVER=0"
      - "CONANEXILES_INSTANCENAME=exiles1"
      - "CONANEXILES_CMDSWITCHES=-Port=7779"
      - "CONANEXILES_CMDSWITCHES=-QueryPort=27017"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=0" # disable rcon
    ports:
        - 7779:7779/udp
        - 27017:27017/udp
    volumes:
        - /gameserver/conan/server2:/conanexiles

  redis:
    image: redis:alpine
    restart: always


volumes:
    data:
        driver: local
```

I don´t see my Mistake!?! 

The picture shows up that there is no start command with Port and Query.. So CMSSWITCHES doesn´t work ????

![htop_conan](https://user-images.githubusercontent.com/38777167/42128732-9d1b6d66-7cb2-11e8-8b29-4321abd650ca.PNG)

The >>docker ps<< shows that the is forwarding 7777 on slave Server.. this is ok or bad ?

![docker_ps_conan](https://user-images.githubusercontent.com/38777167/42128754-2faa9940-7cb3-11e8-9722-e75280ccc1a2.PNG)

**Comment by alinmear** [comment]
CMDSWITCHES is a common env variable. So you must not set it twice. 
It should be: 
  - "CONANEXILES_CMDSWITCHES=-Port=7779 -QueryPort=27017"

**Comment by alinmear** [comment]
This variable should be added to the superviord runcmd; so you could check this within the container at
/etc/supervirord/conf.d/conanexiles.conf

**Comment by xohudson** [comment]
> CMDSWITCHES is a common env variable. So you must not set it twice.
> It should be:
> 
> "CONANEXILES_CMDSWITCHES=-Port=7779 -QueryPort=27017"

This is what i try first .. same error ..

**Comment by alinmear** [comment]
Hm, dont invest more time in testing right now. I just fired up a vps instance for testing this. After i investigated and implemented this properly i will comment here again.

**Comment by xohudson** [comment]
Its my Mistake .. OMG 

I dont have the actual Container.. 

Have pulled it now. SORRY .. i will test it again .. shows good in the first look ..

**Comment by xohudson** [comment]
Sorry .. now it works .. Yiehhaa

The Error was in front of the Display.. 👎 

Thanks for your great work 🥇

**Comment by alinmear** [comment]
Glad to hear that its working!

**Comment by alinmear** [comment]
Just commited changes for the new env variables:

CONANEXILES_PORT
CONANEXILES_QUERYPORT

You could also use these variables for setup instead of the CONANEXILES_CMDSWITCHES

**Comment by hardiselg** [comment]
Hi,

I have tried loads of different configurations however I cant get the server to the general server listing in Conan. Direct connect works perfectly. Can someone spot what I am doing wrong?

```
version:` '2'

services:
  conanexiles:
    image: alinmear/docker-conanexiles:latest
    restart: always
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=XYZAP"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=XYZ"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=XYZP"
#      - "CONANEXILES_Engine_OnlineSubSystemSteam_GameServerQueryPort=27012"
#      - "CONANEXILES_CMDSWITCHES=-MULTIHOME=xxx.xxx.xxx.xxx -NOSTEAM -Port=27028 -QueryPort=27012"
#      - "CONANEXILES_CMDSWITCHES=-MULTIHOME=xxx.xxx.xxx.xxx"
#      - "CONANEXILES_Engine_URL_Port=7777"
#      - "CONANEXILES_Engine_URL_PeerPort=7778"
      - "CONANEXILES_INSTANCENAME=exiles0"
#      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
#      - "CONANEXILES_Game_RconPlugin_RconPassword=XYZAP"
#      - "CONANEXILES_Game_RconPlugin_RconPort=27025"
#      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
      - "CONANEXILES_SERVER_TYPE=pvp"
#      - "CONANEXILES_PORT=27028"
#      - "CONANEXILES_QUERYPORT=27012"
      - "CONANEXILES_ServerSettings_ServerSettings_CombatModeModifier=1"
      - "CONANEXILES_ServerSettings_ServerSettings_PVPEnabled=True"
      - "CONANEXILES_ServerSettings_ServerSettings_RestrictPVPTime=True"
      - "CONANEXILES_ServerSettings_ServerSettings_PVPTimeWeekdayStart=1800"
      - "CONANEXILES_ServerSettings_ServerSettings_PVPTimeWeekdayEnd=2359"
      - "CONANEXILES_ServerSettings_ServerSettings_PVPTimeWeekendStart=1800"
      - "CONANEXILES_ServerSettings_ServerSettings_PVPTimeWeekendEnd=2359"
      - "CONANEXILES_ServerSettings_ServerSettings_RestrictPVPBuildingDamageTime=False"
    ports:
#Direct works, server not listed 
      - 27028:7777/udp
      - 27029:7778/udp
      - 27012:27015/udp
#Testing
#      - 27028:27028/udp
#      - 27029:27029/udp
#      - 27012:27012/udp
#      - 27013:27013/udp

    volumes:
      - data:/conanexiles

volumes:
    data:
        driver: local
```
