### ISSUE TITLE
/usr/bin/redi.sh errors on start

### ISSUE THREAD

**Issue by sjcoder** [alinmear/docker-conanexiles#15]
```root@Z03:~/conan# docker-compose up
Recreating conan_conanexiles_1
Attaching to conan_conanexiles_1
conanexiles_1  | /usr/bin/redi.sh: line 170: redis: Name or service not known
conanexiles_1  | /usr/bin/redi.sh: line 170: FD: Invalid argument
conanexiles_1  | /usr/bin/redi.sh: line 172: $FD: ambiguous redirect
conanexiles_1  | /usr/bin/redi.sh: line 211: $FD: ambiguous redirect
conanexiles_1  | /usr/bin/redi.sh: line 214: FD: ambiguous redirect
```

here's my docker-compose.yml:

```
version: '2'

services:
  conanexiles:
    image: test01
    restart: always
    environment:
        - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=REDACTED"
        - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=REDACTED"
        - "CONANEXILES_ServerSettings_ServerSettings_PlayerXPRateMultiplier=1.5"
        - "CONANEXILES_ServerSettings_ServerSettings_HarvestAmountMultiplier=2"
        - "CONANEXILES_ServerSettings_ServerSettings_CraftingSpeedMultiplier=0.8"
        - "CONANEXILES_ServerSettings_ServerSettings_ClanMaxSize=8"
        - "CONANEXILES_ServerSettings_ServerSettings_MaxAggroRange=500"
        - "CONANEXILES_ServerSettings_ServerSettings_IsBattlEyeEnabled=true"
        - "CONANEXILES_ServerSettings_ServerSettings_RestrictPVPBuildingDamageTime=true"
        - "CONANEXILES_ServerSettings_ServerSettings_PVPBuildingDamageTimeWeekdayStart=1700"
        - "CONANEXILES_ServerSettings_ServerSettings_PVPBuildingDamageTimeWeekdayEnd=2300"
        - "CONANEXILES_ServerSettings_ServerSettings_PVPBuildingDamageTimeWeekendStart=1200"
        - "CONANEXILES_ServerSettings_ServerSettings_PVPBuildingDamageTimeWeekendEnd=0000"
        - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
        - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
        - "CONANEXILES_Game_RconPlugin_RconPort=25575"
        - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
        - "CONANEXILES_ServerSettings_ServerSettings_MinPurgeOnlinePlayers=1"
        - "CONANEXILES_ServerSettings_ServerSettings_PurgeLevel=3"
        - "CONANEXILES_INSTANCENAME=saved"
        - "ENV_CONANEXILES_INSTANCENAME=saved"
        - "ENV_CONANEXILES_MASTERSERVER=1"
        - "CONANEXILES_MASTERSERVER=1"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
        - 25575:25575/udp
        - 25575:25575/tcp
    volumes:
        - /conan-files:/conanexiles
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
```

image is test01 because i changed timezone to US/Central via Dockerfile:
```
FROM alinmear/docker-conanexiles:latest
RUN ln -snf /usr/share/zoneinfo/US/Central /etc/localtime && echo US/Central > /etc/timezone
```
