### ISSUE TITLE
Unable to start server with mods

### ISSUE THREAD

**Issue by otherippo** [alinmear/docker-conanexiles#51]
After setting the sever up and starting it for the first time, all went smooth and I'm able to connect. Then I create the folder "/conanexiles/ConanSandbox/Mods". After adding the file "mods.txt" in it which contains a single mod ID, I'm unable to connect. I can see in the logs that it found the file, the ID it shows is also correct and it downloads the mod. Still even after a server restart I can't connect. How to solve this?

**Comment by h4llm3n** [comment]
I put the *.pak into my folder here /var/lib/docker/volumes/ceserver_data/_data/ConanSandbox/Mods.
All mods are listed in the modlist.txt there with *yourmod.apk per line in it like:

cat modlist.txt
*UIMod_Hosav.pak

I've no problems here to connect to the server. The constant server restarts bother me a bit more.

**Comment by h4llm3n** [comment]
Tried it with the mods.txt. No problems with that option on my end.

**Comment by alinmear** [comment]
I reworked the mods installation; Please use CONANEXILES_MODS=<modid1>,<modid2> for mod installation

**Comment by alinmear** [comment]
Also the restart problematic should be gone; there was a missing check within the controller event loop.

**Comment by h4llm3n** [comment]
@alinmear can you tell me wheres the right place for the variable?

      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
      - "CONANEXILES_UPDATE_SHUTDOWN_TIMER=15"

Somewhere there or somewhere else? I'm confused by the = and now : :D

**Comment by alinmear** [comment]
@h4llm3n  you are right; both are valid yaml syntax (listitem, dict) but maybe confusing, because environment is a list. You have to place it as variables in you compose file:

# Pippi: 880454836 
# Fashionist: 1159180273
# Nilfhein minimap: 1389908968

```yaml
services:
  ce0:
    image: alinmear/docker-conanexiles:latest
    depends_on: 
      - redis
    restart: unless-stopped
    environment:
      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=ThanksForThisSmartSolution"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName=My Cool Server"
      - "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword=MySecret"
      - "CONANEXILES_INSTANCENAME=exiles0"
      - "CONANEXILES_Game_RconPlugin_RconEnabled=1"
      - "CONANEXILES_Game_RconPlugin_RconPassword=REDACTED"
      - "CONANEXILES_Game_RconPlugin_RconPort=25575"
      - "CONANEXILES_Game_RconPlugin_RconMaxKarma=60"
      - "CONANEXILES_MODS=880454836,1159180273,1389908968"
    ports:
        - 7777:7777/udp
        - 7778:7778/udp
        - 27015:27015/udp
    volumes:
        - data:/conanexiles
```
